/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softmasters.dawuro.umid;

import java.util.List;

public class SuccessPojo {


    //applicantid generated by server
    private String applicantid;
    private String status;
    //applicantid generated by phone
    private String mobileapplicantid;
    //businessid generated by phone
    private String mobilebusuid;
    private String busuid;
    // new field
    private List<ResponseEntity> responseentity;

    public String getApplicantid() {
        return applicantid;
    }

    public void setApplicantid(String applicantid) {
        this.applicantid = applicantid;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMobileapplicantid() {
        return mobileapplicantid;
    }

    public void setMobileapplicantid(String mobileapplicantid) {
        this.mobileapplicantid = mobileapplicantid;
    }

    public String getMobilebusuid() {
        return mobilebusuid;
    }

    public void setMobilebusuid(String mobilebusuid) {
        this.mobilebusuid = mobilebusuid;
    }

    public String getBusuid() {
        return busuid;
    }

    public void setBusuid(String busuid) {
        this.busuid = busuid;
    }

    public List<ResponseEntity> getResponseentity() {
        return responseentity;
    }

    public void setResponseentity(List<ResponseEntity> responseentity) {
        this.responseentity = responseentity;
    }
}
